EMAIL_TOOL_DECLARATIONS = [
    {
        "name": "get_emails",
        "description": "Gmail hesabında email axtarır və uyğun mesajların göndərən, mövzu, tarix və qısa məzmununu qaytarır. Qovluq sorğularında folder parametrini mütləq istifadə et: inbox, sent, drafts, spam, trash, promotions, social, updates, purchases, starred, all_mail.",
        "parameters": {"type": "OBJECT", "properties": {"query": {"type": "STRING", "description": "Əlavə Gmail search query."}, "folder": {"type": "STRING", "description": "Gmail qovluğu."}, "limit": {"type": "NUMBER", "description": "Maksimum email sayı."}}}
    },
    {"name": "read_email_thread", "description": "Gmail thread-dəki bütün mesajları oxuyur. thread_id əvvəlki email nəticəsindən alınmalıdır.", "parameters": {"type": "OBJECT", "properties": {"thread_id": {"type": "STRING", "description": "Gmail thread ID."}}, "required": ["thread_id"]}},
    {"name": "prepare_trash_emails", "description": "Gmail email(lər)ini Trash-a göndərmək üçün əvvəlcə dəqiq snapshot hazırlayır. Heç nə silmir; confirmation_id yaradır və açıq təsdiq tələb edir.", "parameters": {"type": "OBJECT", "properties": {"folder": {"type": "STRING"}, "message_id": {"type": "STRING"}, "query": {"type": "STRING"}}}},
    {"name": "trash_emails", "description": "Yalnız istifadəçinin açıq təsdiqindən sonra əvvəlki snapshot-ı Trash-a göndərir.", "parameters": {"type": "OBJECT", "properties": {"confirmation_id": {"type": "STRING"}}, "required": ["confirmation_id"]}},
    {"name": "prepare_email_deletion", "description": "Gmail üçün permanent delete planı hazırlayır və confirmation tələb edir.", "parameters": {"type": "OBJECT", "properties": {"scope": {"type": "STRING", "enum": ["drafts", "draft", "spam", "trash", "promotions", "social"]}, "draft_id": {"type": "STRING"}}, "required": ["scope"]}},
    {"name": "delete_email", "description": "Yalnız əvvəlcədən hazırlanmış və istifadəçi tərəfindən təsdiqlənmiş Gmail silmə planını icra edir.", "parameters": {"type": "OBJECT", "properties": {"confirmation_id": {"type": "STRING"}}, "required": ["confirmation_id"]}},
    {"name": "read_email", "description": "Gmail-da message_id ilə konkret emaili oxuyur.", "parameters": {"type": "OBJECT", "properties": {"message_id": {"type": "STRING"}}, "required": ["message_id"]}},
    {"name": "prepare_email_reply", "description": "Mövcud Gmail emailinə cavab hazırlayır və Draft yaradır. Email göndərilmir; sonrakı göndəriş üçün açıq istifadəçi təsdiqi tələb olunur.", "parameters": {"type": "OBJECT", "properties": {"message_id": {"type": "STRING"}, "body": {"type": "STRING"}}, "required": ["message_id", "body"]}},
    {"name": "prepare_new_email", "description": "Yeni Gmail Draft yaradır. Email göndərilmir; sonrakı göndəriş üçün açıq istifadəçi təsdiqi tələb olunur.", "parameters": {"type": "OBJECT", "properties": {"to": {"type": "STRING"}, "subject": {"type": "STRING"}, "body": {"type": "STRING"}, "cc": {"type": "STRING"}, "bcc": {"type": "STRING"}}, "required": ["to", "subject", "body"]}},
    {"name": "send_email", "description": "Gmail Draft-ı göndərir. Yalnız istifadəçi həmin draftın göndərilməsini açıq şəkildə təsdiqlədikdən sonra çağırılmalıdır. confirmation_id olmadan göndəriş icra edilmir.", "parameters": {"type": "OBJECT", "properties": {"draft_id": {"type": "STRING"}, "confirmation_id": {"type": "STRING", "description": "Təsdiqlənmiş göndəriş identifikatoru."}}, "required": ["draft_id"]}},
    {"name": "sync_google_contacts", "description": "Google Contacts-dakı kontaktları local phone_book.json ilə sinxronizasiya edir.", "parameters": {"type": "OBJECT", "properties": {}}}
]
