import tool_defs as _tool_defs

_tool_defs.TOOL_DECLARATIONS[:] = [item for item in _tool_defs.TOOL_DECLARATIONS if item.get("name") != "add_reminder"]

TASK_TOOL_DECLARATIONS = [
    {"name": "confirm_action", "description": "Əvvəlki riskli əməliyyat üçün istifadəçidən açıq təsdiq alındıqdan sonra verilmiş confirmation_id ilə əməliyyatı icra edir. Yalnız istifadəçi açıq şəkildə təsdiqlədikdən sonra çağır.", "parameters": {"type": "OBJECT", "properties": {"confirmation_id": {"type": "STRING"}}, "required": ["confirmation_id"]}},
    {"name": "get_eva_reminders", "description": "Google Tasks-dan tam ayrı olan EVA yaddaşındakı xatırlatmaları oxuyur.", "parameters": {"type": "OBJECT", "properties": {"query": {"type": "STRING", "description": "today | upcoming | completed | all və ya axtarış mətni"}, "limit": {"type": "NUMBER"}}}},
    {"name": "add_eva_reminder", "description": "Xatırlatmanı yalnız EVA local memory-də yaradır. Google Tasks-a yazmır.", "parameters": {"type": "OBJECT", "properties": {"title": {"type": "STRING"}, "due_iso": {"type": "STRING"}, "notes": {"type": "STRING"}}, "required": ["title"]}},
    {"name": "update_eva_reminder", "description": "EVA memory-dəki xatırlatmanı yeniləyir.", "parameters": {"type": "OBJECT", "properties": {"reminder_id": {"type": "STRING"}, "title": {"type": "STRING"}, "due_iso": {"type": "STRING"}, "notes": {"type": "STRING"}}, "required": ["reminder_id"]}},
    {"name": "complete_eva_reminder", "description": "EVA memory xatırlatmasını tamamlandı kimi işarələyir.", "parameters": {"type": "OBJECT", "properties": {"reminder_id": {"type": "STRING"}}, "required": ["reminder_id"]}},
    {"name": "delete_eva_reminder", "description": "EVA memory xatırlatmasını silir. Əvvəlcə açıq istifadəçi təsdiqi tələb olunur və confirm_action istifadə edilməlidir.", "parameters": {"type": "OBJECT", "properties": {"reminder_id": {"type": "STRING"}, "confirmation_id": {"type": "STRING"}}, "required": ["reminder_id"]}},
    {"name": "update_reminder", "description": "Google Tasks-da mövcud tapşırığı yeniləyir. Başlıq, son tarix və ya qeyd dəyişdirilə bilər.", "parameters": {"type": "OBJECT", "properties": {"task_id": {"type": "STRING"}, "title": {"type": "STRING"}, "due_iso": {"type": "STRING"}, "notes": {"type": "STRING"}, "list_name": {"type": "STRING"}, "all_day": {"type": "BOOLEAN"}}, "required": ["task_id"]}},
    {"name": "complete_reminder", "description": "Google Tasks-da tapşırığı tamamlandı kimi işarələyir.", "parameters": {"type": "OBJECT", "properties": {"task_id": {"type": "STRING"}, "list_name": {"type": "STRING"}}, "required": ["task_id"]}},
    {"name": "delete_reminder", "description": "Google Tasks-dan konkret tapşırığı silir. Əməliyyat üçün əvvəlcə açıq istifadəçi təsdiqi alınmalıdır.", "parameters": {"type": "OBJECT", "properties": {"task_id": {"type": "STRING"}, "list_name": {"type": "STRING"}, "confirmation_id": {"type": "STRING"}}, "required": ["task_id"]}},
    {"name": "get_daily_agenda", "description": "Bu gün üçün Google Calendar, Google Tasks və EVA memory-də saxlanmış agenda qeydlərini vahid nəticədə oxuyur.", "parameters": {"type": "OBJECT", "properties": {"limit": {"type": "NUMBER"}}}},
    {"name": "add_agenda_item", "description": "Task və ya qeyd əlavə edir. İstifadəçi Google Tasks və ya EVA yaddaşı arasında seçim edə bilər.", "parameters": {"type": "OBJECT", "properties": {"title": {"type": "STRING"}, "item_type": {"type": "STRING"}, "storage": {"type": "STRING"}, "due_iso": {"type": "STRING"}, "notes": {"type": "STRING"}}, "required": ["title"]}},
    {"name": "delete_agenda_item", "description": "Task və ya qeydi silir. Bir neçə uyğunluqda silmə etmir və açıq təsdiq tələb edir.", "parameters": {"type": "OBJECT", "properties": {"match_text": {"type": "STRING"}, "storage": {"type": "STRING"}, "confirm": {"type": "BOOLEAN"}}, "required": ["match_text"]}},
    {"name": "query_unified_assistant", "description": "Təbii dildə cross-source məlumat sorğusunu vahid şəkildə planlayır və Calendar, Google Tasks, Memory, Gmail və WhatsApp mənbələrini birlikdə yoxlayır.", "parameters": {"type": "OBJECT", "properties": {"query": {"type": "STRING"}, "limit": {"type": "NUMBER"}}, "required": ["query"]}},
]
